export const MAIN_PATH = (category: string = 'All') => `/${category}`;
export const AUTH_PATH = () => '/auth';
export const SEARCH_PATH = (searchWord: string) => `/search/${searchWord}`;
export const USER_PATH = (userEmail: string) => `/user/${userEmail}`;
export const BOARD_PATH = () => '/board';
export const BOARD_DETAIL_PATH = (category: string, boardNumber: string | number) => `${category}/detail/${boardNumber}`;
export const BOARD_WRITE_PATH = () => 'write';
export const BOARD_UPDATE_PATH = (boardNumber: string | number) => `update/${boardNumber}`;
export const YOUTUBE_PATH = () => '/youtube';
export const YOUTUBE_SEARCH_PATH = (searchWord: string) => `/youtube/${searchWord}`;
export const YOUTUBE_TREND_PATH = () => '/youtube/trending';