enum ColorMap {
    CUSTOM_COLOR_DEFAULT = "#000000", 
    CUSTOM_COLOR_GRAY = "#808080",
    CUSTOM_COLOR_BROWN = "#A52A2A",
    CUSTOM_COLOR_ORANGE = "#FFA500",
    CUSTOM_COLOR_YELLOW = "#FFFF00",
    CUSTOM_COLOR_GREEN = "#008000",
    CUSTOM_COLOR_BLUE = "#0000FF",
    CUSTOM_COLOR_PURPLE = "#800080",
    CUSTOM_COLOR_PINK = "#FFC0CB",
    CUSTOM_COLOR_RED = "#FF0000",
    CUSTOM_BACKGROUND_DEFAULT = "#FFFFFF",
    CUSTOM_BACKGROUND_GRAY = "#F0F0F0",
    CUSTOM_BACKGROUND_BROWN = "#D2B48C",
    CUSTOM_BACKGROUND_ORANGE = "#FFE4B5",
    CUSTOM_BACKGROUND_YELLOW = "#FFFACD",
    CUSTOM_BACKGROUND_GREEN = "#E0FFE0",
    CUSTOM_BACKGROUND_BLUE = "#E0F7FF",
    CUSTOM_BACKGROUND_PURPLE = "#F3E5F5",
    CUSTOM_BACKGROUND_PINK = "#FFEBE9",
    CUSTOM_BACKGROUND_RED = "#FFE6E6",
}

export default ColorMap